/**
 * TR_027 / ADR-051 — generate `.pr_agent.toml` from a project's
 * `HARNESS.json`.
 *
 * The single source of truth for project review rules is
 * `HARNESS.json.agentConfig`. PR-Agent's `[pr_reviewer]
 * extra_instructions` is a renderer of those rules — operators
 * edit HARNESS.json and the platform regenerates this file
 * (at `gestalt init`, or via
 * `gestalt project config push-pr-agent-config`).
 *
 * Pure function — given a parsed HarnessConfig, returns the
 * `.pr_agent.toml` content. Never throws; missing agentConfig
 * blocks render as empty rule lists.
 */

import type { HarnessConfig } from '@gestalt/core';

const TOML_HEADER =
  `# Generated by Gestalt from HARNESS.json — do NOT edit by hand.\n` +
  `# Edit HARNESS.json.agentConfig['review-agent'].rules /\n` +
  `# agentConfig['constraint-agent'].rules and run\n` +
  `# 'gestalt project config push-pr-agent-config' to refresh.\n` +
  `#\n` +
  `# ADR-051 — CodiumAI PR-Agent replaces the custom review-agent\n` +
  `# on github-actions pipelines.\n`;

export function generatePrAgentToml(harnessConfig: HarnessConfig | null): string {
  const reviewRules = harnessConfig?.agentConfig?.['review-agent']?.rules ?? [];
  const constraintRules = harnessConfig?.agentConfig?.['constraint-agent']?.rules ?? [];

  // Concat + de-dup while preserving order. The same rule may live
  // under both agents (operators sometimes copy a critical
  // architectural rule into both blocks); we render once.
  const seen = new Set<string>();
  const merged: string[] = [];
  for (const rule of [...constraintRules, ...reviewRules]) {
    const trimmed = rule.trim();
    if (!trimmed || seen.has(trimmed)) continue;
    seen.add(trimmed);
    merged.push(trimmed);
  }

  const rulesBlock = merged.length > 0
    ? merged.map((r) => `- ${escapeForToml(r)}`).join('\n')
    : '- (no project-specific architectural rules declared)';

  return [
    TOML_HEADER,
    '',
    '[pr_reviewer]',
    'extra_instructions = """',
    'This project enforces the following architectural rules.',
    'Flag any violations in your review:',
    '',
    rulesBlock,
    '"""',
    '',
    '[pr_description]',
    'extra_instructions = """',
    'Summarise the change in the context of the feature or fix',
    'this PR is implementing. Reference the intent that generated it.',
    '"""',
    '',
    '[pr_code_suggestions]',
    'extra_instructions = """',
    'When suggesting fixes, keep them consistent with the project',
    'architecture described above.',
    '"""',
    '',
  ].join('\n');
}

/**
 * Defensive escape for triple-quoted TOML strings. The brief's
 * format uses `"""` delimiters, so a rule containing a literal
 * `"""` would terminate the string early. Escape by collapsing.
 * Backslashes pass through; newlines in a rule become a single
 * space (TOML allows it, but it keeps the rendered toml compact).
 */
function escapeForToml(s: string): string {
  return s
    .replace(/"""/g, '\\"\\"\\"')
    .replace(/\r?\n/g, ' ');
}
