/**
 * LLM review agent — qualitative code review.
 *
 * Sends the artifact set to the platform LLM with a structured-output
 * prompt asking for concerns about:
 *   - security (input validation, injection, auth)
 *   - architecture (module boundaries, separation of concerns)
 *   - golden-principle adherence (audit on mutation, RBAC, etc.)
 *   - clear bugs (missing error handling, dangling references)
 *
 * The full prose review is persisted as an artifact (`.gestalt/llm-review-
 * <correlationId>.md`) so the operator can read the qualitative feedback
 * even when the verdict is `pass`. Concrete blocking concerns are also
 * emitted as `CONSTRAINT_VIOLATION` / `GOLDEN_PRINCIPLE_BREACH` signals;
 * low/info-severity comments stay in the artifact only and do not fail
 * the gate.
 */

import type { ArtifactRef, GateAgentResult, GateSignal, GateTask } from '../types';
import type { Artifact, SignalSeverity } from '@gestalt/core';

interface LLMReviewItem {
  file?: string;
  line?: number;
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
  category: 'security' | 'architecture' | 'golden-principle' | 'bug' | 'style';
  message: string;
  fixHint?: string;
}

interface LLMReview {
  summary: string;
  overallVerdict: 'pass' | 'concerns' | 'block';
  items: LLMReviewItem[];
}

export interface LLMReviewArtifact extends Artifact {
  type: 'design';
}

export interface LLMReviewAgentResult extends GateAgentResult {
  reviewArtifact: LLMReviewArtifact | null;
}

const MAX_ARTIFACT_BYTES = 8000;   // per file, when bundling into the prompt
const MAX_TOTAL_BYTES = 60_000;    // prompt budget guard

/**
 * Runs the LLM review agent against the artifact set in the task.
 * The caller (gate orchestrator) is expected to invoke this with an
 * `llmCall` that returns the model's raw text response.
 */
export async function runLlmReviewAgent(
  task: GateTask,
  llmCall: (prompt: string) => Promise<string>,
): Promise<LLMReviewAgentResult> {
  const startedAt = Date.now();

  const codeArtifacts = task.artifacts.filter(
    (a) => a.type === 'code' || a.type === 'test' || a.type === 'context-file',
  );

  if (codeArtifacts.length === 0) {
    return {
      agentRole: 'review-agent',
      status: 'passed',
      signals: [],
      durationMs: Date.now() - startedAt,
      reviewArtifact: null,
    };
  }

  const prompt = buildReviewPrompt(codeArtifacts, task.harnessConfig.goldenPrinciples);

  let review: LLMReview;
  try {
    const raw = await llmCall(prompt);
    review = parseReview(raw);
  } catch (err) {
    // The LLM call or JSON parse failed. Treat as an `errored` agent run —
    // gate verdict treats it as an absence of signals (pass through),
    // operator sees the error in the agent_executions row.
    return {
      agentRole: 'review-agent',
      status: 'errored',
      signals: [],
      durationMs: Date.now() - startedAt,
      reviewArtifact: null,
    };
  }

  const signals = mapItemsToSignals(task.correlationId, review.items);

  const reviewArtifact: LLMReviewArtifact = {
    id: crypto.randomUUID(),
    correlationId: task.correlationId,
    type: 'design',
    path: `.gestalt/llm-review-${task.correlationId.slice(0, 8)}.md`,
    content: renderReviewMarkdown(review),
    producedBy: 'review-agent',
    createdAt: new Date(),
  };

  return {
    agentRole: 'review-agent',
    status: signals.length === 0 ? 'passed' : 'failed',
    signals,
    durationMs: Date.now() - startedAt,
    reviewArtifact,
  };
}

// ─── Prompt + parsing ────────────────────────────────────────────────────────

function buildReviewPrompt(artifacts: ArtifactRef[], goldenPrinciples: string[]): string {
  let used = 0;
  const files: string[] = [];
  for (const a of artifacts) {
    if (used > MAX_TOTAL_BYTES) break;
    const slice = a.content.length > MAX_ARTIFACT_BYTES
      ? `${a.content.slice(0, MAX_ARTIFACT_BYTES)}\n/* TRUNCATED */`
      : a.content;
    files.push(`### ${a.path}\n\n\`\`\`\n${slice}\n\`\`\``);
    used += slice.length;
  }

  const principles = goldenPrinciples.length
    ? goldenPrinciples.map((p) => `- ${p}`).join('\n')
    : '- (none supplied)';

  return `You are the quality-gate review agent for the Gestalt platform.

You are reviewing code generated by upstream agents. Your job is to
identify concerns the generate layer missed. Be specific and concrete —
no generic advice. Only flag concerns that are actually present in the
code below.

## Golden principles for this project

${principles}

## Files under review

${files.join('\n\n')}

## Instructions

Return ONLY a JSON object (no preamble, no markdown fences) matching this
schema:

{
  "summary": "<2-4 sentence overall judgment>",
  "overallVerdict": "<pass | concerns | block>",
  "items": [
    {
      "file": "<path of the file the concern is in>",
      "line": <1-based line number, or omit if file-wide>,
      "severity": "<critical | high | medium | low | info>",
      "category": "<security | architecture | golden-principle | bug | style>",
      "message": "<one-sentence specific concern>",
      "fixHint": "<one-sentence suggested fix, optional>"
    }
  ]
}

Severity rules:
- critical: security issue with immediate impact (hardcoded secret, unguarded SQL, etc.) — blocks merge
- high: golden-principle breach (missing audit on mutation, RBAC bypass, direct DB call outside repo)
- medium: real bug or architectural drift that should be fixed
- low: minor stylistic or minor consistency issue
- info: observation worth noting, not a problem

If the code is clean, return overallVerdict: "pass" and an empty items array.
`;
}

function parseReview(raw: string): LLMReview {
  const clean = raw.replace(/```json|```/g, '').trim();
  // Some models wrap the JSON in surrounding prose. Find the outermost {...}.
  const start = clean.indexOf('{');
  const end = clean.lastIndexOf('}');
  const body = start >= 0 && end > start ? clean.slice(start, end + 1) : clean;
  const parsed = JSON.parse(body) as Partial<LLMReview>;
  return {
    summary: typeof parsed.summary === 'string' ? parsed.summary : '',
    overallVerdict: parsed.overallVerdict ?? 'pass',
    items: Array.isArray(parsed.items)
      ? parsed.items.filter((i): i is LLMReviewItem =>
        !!i && typeof i.message === 'string' && typeof i.severity === 'string' && typeof i.category === 'string',
      )
      : [],
  };
}

// ─── Signal mapping ──────────────────────────────────────────────────────────

function mapItemsToSignals(
  correlationId: string,
  items: LLMReviewItem[],
): GateSignal[] {
  const out: GateSignal[] = [];
  for (const item of items) {
    // Only critical / high produce blocking signals. medium → still a
    // CONSTRAINT_VIOLATION so the code-agent can fix it on retry. low/info
    // stay in the artifact only.
    if (item.severity === 'low' || item.severity === 'info') continue;

    // GOLDEN_PRINCIPLE_BREACH triggers `escalate` (human review, never
    // auto-resolved). Reserve it for `critical` severity only — that
    // means actual security threats: hardcoded secrets, unguarded SQL,
    // RBAC bypass. "Missing input validation" or "could improve audit
    // logging" are fixable issues that should route back to the code-
    // agent via CONSTRAINT_VIOLATION, not escalate to a human.
    const isBreach = item.severity === 'critical';

    out.push({
      id: crypto.randomUUID(),
      correlationId,
      type: isBreach ? 'GOLDEN_PRINCIPLE_BREACH' : 'CONSTRAINT_VIOLATION',
      severity: mapSeverity(item.severity),
      agentRole: 'review-agent',
      message: `[review/${item.category}] ${item.message}${item.fixHint ? ` Hint: ${item.fixHint}` : ''}`,
      location: item.file
        ? { file: item.file, line: item.line, rule: `review/${item.category}` }
        : null,
      autoResolvable: !isBreach,
    });
  }
  return out;
}

function mapSeverity(s: LLMReviewItem['severity']): SignalSeverity {
  if (s === 'critical') return 'critical';
  if (s === 'high') return 'high';
  if (s === 'medium') return 'medium';
  return 'low';
}

// ─── Artifact rendering ──────────────────────────────────────────────────────

function renderReviewMarkdown(review: LLMReview): string {
  const lines = [
    '# LLM quality-gate review',
    '',
    `**Overall verdict:** ${review.overallVerdict}`,
    '',
    '## Summary',
    '',
    review.summary || '_(no summary)_',
    '',
  ];

  if (review.items.length === 0) {
    lines.push('## Items', '', '_No concerns flagged._', '');
    return lines.join('\n');
  }

  lines.push('## Items', '');
  for (const item of review.items) {
    const loc = item.file
      ? item.line
        ? `${item.file}:${item.line}`
        : item.file
      : '(file-wide)';
    lines.push(`### ${item.severity.toUpperCase()} · ${item.category} · ${loc}`);
    lines.push('');
    lines.push(item.message);
    if (item.fixHint) {
      lines.push('');
      lines.push(`**Suggested fix:** ${item.fixHint}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}
